# Generated by Django 5.1.2 on 2024-10-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Revent',
        ),
        migrations.RenameModel(
            old_name='GroupNote',
            new_name='ReventNote',
        ),
        migrations.RenameField(
            model_name='reventnote',
            old_name='in_group',
            new_name='in_revent',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='in_group',
            new_name='in_revent',
        ),
    ]
