# Generated by Django 5.1.2 on 2024-11-06 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0004_rename_secret_contactinfo_info_contactinfo_in_revent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reventnote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
