# Generated by Django 5.1.2 on 2024-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0005_reventnote_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reventnote',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-seq']},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='info_type',
            field=models.CharField(choices=[('OTHR', 'Other Contact Address'), ('MAIL', 'Email Address'), ('PHON', 'Phone Number'), ('WEBS', 'Organization Website URL'), ('YOUT', 'Youtube URL'), ('TWTR', 'X (formerly twitter) URL'), ('FCBK', 'Facebook URL'), ('INSG', 'Instagram URL'), ('LNIN', 'LinkedIn URL'), ('VIME', 'Vimeo URL'), ('WHAP', 'WhatsApp group URL'), ('TLGM', 'Telegram group URL'), ('DCRD', 'Discord group URL'), ('SLAK', 'Slack group URL'), ('GCHG', 'Gamechanger Action Tracker URL'), ('FMAP', 'FFF Map URL')], max_length=4),
        ),
    ]
