# Generated by Django 3.1.2 on 2020-10-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_prefix', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('regid', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('gathering_type', models.CharField(choices=[('STRK', 'Strike'), ('DEMO', 'Demonstration'), ('NVDA', 'Non-Violent Direct Action'), ('MEET', 'Meetup'), ('OTHR', 'Other')], default='STRK', max_length=4)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField(blank=True)),
                ('duration', models.DurationField(blank=True)),
                ('expected_participants', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('in_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.country')),
                ('in_location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='action.location')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=25)),
                ('home_zip', models.CharField(blank=True, max_length=12)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('visibility_level', models.CharField(choices=[('SIGN', 'Only callsign'), ('PRIV', '+ Country, State, Zip, Organizations'), ('FRND', '+ Email (to friends and trusted organizations)'), ('PUBL', '+ Email (to the world)'), ('OPEN', '+ Phone and contact notes')], default='SIGN', max_length=4)),
                ('contact_notes', models.CharField(blank=True, max_length=200)),
                ('home_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='action.country')),
                ('home_state', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='action.location')),
                ('organizations', models.ManyToManyField(blank=True, to='action.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('claim', models.FloatField(default=1, editable=False)),
                ('strength', models.FloatField(default=0, editable=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='action.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='action.verification'),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='action.verification'),
        ),
        migrations.AddField(
            model_name='location',
            name='verified',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='action.verification'),
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=2000)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives_creator', to='action.user')),
                ('crew_users', models.ManyToManyField(blank=True, related_name='initiatives_crew', to='action.User')),
                ('interested_users', models.ManyToManyField(blank=True, related_name='initiatives_interest', to='action.User')),
            ],
        ),
        migrations.CreateModel(
            name='Gathering_Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('participants', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('gathering', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.gathering')),
                ('witness', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.user')),
            ],
        ),
        migrations.AddField(
            model_name='gathering',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.location'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('registration_source', models.CharField(editable=False, max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=2000)),
                ('action_link', models.URLField()),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_creator', to='action.user')),
                ('crew_users', models.ManyToManyField(blank=True, related_name='actions_crew', to='action.User')),
                ('interested_users', models.ManyToManyField(blank=True, related_name='actions_interest', to='action.User')),
            ],
        ),
    ]
