# Generated by Django 3.1.2 on 2020-10-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='crew_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='actions_crew', to='action.User'),
        ),
        migrations.AlterField(
            model_name='action',
            name='interested_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='actions_interest', to='action.User'),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='expected_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='crew_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='initiatives_crew', to='action.User'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='interested_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='initiatives_interest', to='action.User'),
        ),
        migrations.AlterField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, to='action.Organization'),
        ),
    ]
