# Generated by Django 3.1.2 on 2020-10-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20201007_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='crew_users',
            field=models.ManyToManyField(blank=True, related_name='actions_crew', to='action.User'),
        ),
        migrations.AlterField(
            model_name='action',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='actions_interest', to='action.User'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='crew_users',
            field=models.ManyToManyField(blank=True, related_name='initiatives_crew', to='action.User'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='initiatives_interest', to='action.User'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='action.Organization'),
        ),
    ]
