# Generated by Django 3.1.2 on 2020-10-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20201007_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
    ]
