# Generated by Django 3.1.2 on 2020-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_auto_20201007_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering_witness',
            name='proof_url',
            field=models.URLField(blank=True),
        ),
    ]
