# Generated by Django 3.1.2 on 2020-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_gathering_witness_proof_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering_witness',
            name='date',
            field=models.DateField(),
        ),
    ]
