# Generated by Django 3.1.2 on 2020-10-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_auto_20201007_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='in_country',
        ),
    ]
