# Generated by Django 3.1.2 on 2020-10-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_remove_location_in_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering_Belong',
            fields=[
                ('regid', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.gathering')),
            ],
        ),
    ]
