# Generated by Django 3.1.2 on 2020-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0009_auto_20201011_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering_witness',
            name='participants',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
