# Generated by Django 3.1.2 on 2020-11-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0010_auto_20201030_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserHome',
        ),
    ]
