# Generated by Django 3.1.2 on 2020-11-30 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action', '0011_auto_20201130_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhome',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userhome',
            name='id',
        ),
        migrations.AddField(
            model_name='userhome',
            name='loginuser',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='callsign',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
