# Generated by Django 3.1.2 on 2020-11-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0012_auto_20201130_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhome',
            name='screenname',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
