# Generated by Django 3.1.2 on 2020-11-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_userhome_screenname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='contact_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='home_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.country'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='home_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.location'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='home_zip',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, to='action.Organization'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='screenname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
