# Generated by Django 3.1.2 on 2020-12-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0015_auto_20201209_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering_witness',
            name='proof_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='visibility_level',
            field=models.CharField(choices=[('SIGN', 'Callsign only'), ('PRIV', 'Callsign, Country, State, Zip, Organizations'), ('FRND', 'Callsign, Country, State, Zip, Organizations, Closed Email (to friends and trusted organizations only)'), ('PUBL', 'Callsign, Country, State, Zip, Organizations, Open Email (to the world)'), ('OPEN', 'Callsign, Country, State, Zip, Organizations, Open Email, Phone and contact notes')], default='SIGN', max_length=4),
        ),
    ]
