# Generated by Django 3.1.2 on 2020-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0016_auto_20201222_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_link',
            field=models.URLField(max_length=500),
        ),
    ]
