# Generated by Django 3.1.2 on 2021-01-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0017_auto_20201230_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
