# Generated by Django 3.1.2 on 2021-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0018_auto_20210124_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='action.Organization'),
        ),
    ]
