# Generated by Django 3.1.2 on 2021-03-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0019_gathering_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering_witness',
            name='organization',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.organization'),
        ),
    ]
