# Generated by Django 3.1.7 on 2021-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0020_gathering_witness_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhome',
            name='loginuser',
        ),
        migrations.RemoveField(
            model_name='userhome',
            name='organizations',
        ),
        migrations.AddField(
            model_name='userhome',
            name='loginuser_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
