# Generated by Django 3.1.7 on 2021-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0021_auto_20210329_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='expected_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gathering_witness',
            name='participants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
