# Generated by Django 3.1.7 on 2021-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0022_auto_20210329_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gathering',
            name='contact_email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gathering',
            name='contact_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gathering',
            name='contact_notes',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gathering',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gathering',
            name='time',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
