# Generated by Django 4.1.7 on 2023-12-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0025_alter_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='primary_email',
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.location'),
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacttype', models.CharField(choices=[('MAIL', 'Email Adress'), ('PHON', 'Phone Number'), ('OTHR', 'Other Contact Adress')], default='OTHR', max_length=4)),
                ('adress', models.CharField(max_length=200)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.organization')),
            ],
        ),
    ]
