# Generated by Django 4.1.7 on 2023-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0026_rename_email_organization_primary_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='contacttype',
            field=models.CharField(choices=[('OTHR', 'Other Contact Adress'), ('MAIL', 'Email Adress'), ('PHON', 'Phone Number'), ('WEBS', 'Organization Website URL'), ('TWTR', 'X (formerly twitter) URL'), ('FCBK', 'Facebook URL'), ('INSG', 'Instagram URL')], default='OTHR', max_length=4),
        ),
    ]
