# Generated by Django 4.1.7 on 2023-12-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0028_contact_remove_organization_primary_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contacts',
        ),
    ]
