# Generated by Django 4.1.7 on 2023-12-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0029_remove_organization_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
