# Generated by Django 4.1.7 on 2023-12-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0030_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='primary_location',
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.location'),
        ),
    ]
