# Generated by Django 4.1.7 on 2023-12-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0034_alter_organizationcontact_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationcontact',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
