# Generated by Django 4.1.7 on 2023-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0036_organizationcontact_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
