# Generated by Django 4.1.7 on 2024-01-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0038_alter_organizationcontact_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='locadion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='action.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationcontact',
            name='contacttype',
            field=models.CharField(choices=[('OTHR', 'Other Contact Address'), ('MAIL', 'Email Address'), ('PHON', 'Phone Number'), ('WEBS', 'Organization Website URL'), ('YOUT', 'Youtube URL'), ('TWTR', 'X (formerly twitter) URL'), ('FCBK', 'Facebook URL'), ('INSG', 'Instagram URL'), ('LNIN', 'LinkedIn URL'), ('VIME', 'Vimeo URL'), ('WHAP', 'WhatsApp group URL'), ('TLGM', 'Telegram group URL'), ('DCRD', 'Discord group URL'), ('SLAK', 'Slack group URL')], default='OTHR', max_length=4),
        ),
    ]
