# Generated by Django 4.1.7 on 2024-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0040_alter_organizationcontact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
