# Generated by Django 4.1.7 on 2024-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0043_alter_organizationcontact_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontact',
            name='locationTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='organizationTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
