# Generated by Django 4.1.7 on 2024-01-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0044_organizationcontact_locationtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.location'),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
