# Generated by Django 4.1.7 on 2024-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0045_alter_gathering_location_alter_gathering_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
