# Generated by Django 4.1.7 on 2024-01-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0046_country_code_country_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='locadion',
            new_name='location',
        ),
    ]
