# Generated by Django 4.1.7 on 2024-01-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0047_rename_locadion_country_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='in_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.country'),
        ),
    ]
