# Generated by Django 4.1.7 on 2024-03-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0049_location_google_name_alter_gathering_gathering_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='google_name',
        ),
        migrations.AddField(
            model_name='location',
            name='google_metadata',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='verified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.verification'),
        ),
    ]
