# Generated by Django 4.1.7 on 2024-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0050_remove_location_google_name_location_google_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='details',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
