# Generated by Django 4.1.7 on 2024-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0051_verification_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='verified',
        ),
        migrations.AddField(
            model_name='location',
            name='creation_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_metadata',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='callsign',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
