# Generated by Django 4.1.7 on 2024-04-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0053_location_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_belong',
            name='duplicate',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='action.location'),
        ),
    ]
