# Generated by Django 4.1.7 on 2024-04-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0054_alter_location_belong_duplicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='location_belong',
            name='duplicate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='action.location'),
        ),
        migrations.AddField(
            model_name='gathering',
            name='steward',
            field=models.ManyToManyField(blank=True, null=True, to='action.steward'),
        ),
    ]
