# Generated by Django 4.1.7 on 2024-04-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0055_steward_alter_location_belong_duplicate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathering',
            name='steward',
        ),
        migrations.AddField(
            model_name='gathering',
            name='steward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.steward'),
        ),
    ]
