# Generated by Django 5.1.2 on 2024-12-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0056_remove_gathering_steward_gathering_steward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('steward_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.steward')),
            ],
            bases=('action.steward',),
        ),
        migrations.AddField(
            model_name='gathering',
            name='event_link_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='steward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steward_of_gathering', to='action.steward'),
        ),
        migrations.AddField(
            model_name='gathering',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_of_gathering', to='action.guide'),
        ),
    ]
