# Generated by Django 5.1.2 on 2025-01-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0057_guide_gathering_event_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='contact_email',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='contact_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='contact_notes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
