# Generated by Django 5.1.2 on 2025-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0058_alter_gathering_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey_str', models.CharField(editable=False, max_length=80)),
                ('created_on', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
