# Generated by Django 5.1.2 on 2025-02-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0059_pubkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering_witness',
            name='steward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steward_of_gwitness', to='action.steward'),
        ),
    ]
