# Generated by Django 5.1.2 on 2025-02-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0060_gathering_witness_steward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('steward_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.steward')),
            ],
            bases=('action.steward',),
        ),
        migrations.AddField(
            model_name='gathering_witness',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_of_gwitness', to='action.guide'),
        ),
        migrations.AddField(
            model_name='gathering',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_of_gathering', to='action.coordinator'),
        ),
        migrations.AddField(
            model_name='gathering_witness',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_of_gwitness', to='action.coordinator'),
        ),
    ]
