# Generated by Django 5.1.2 on 2025-02-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0061_coordinator_gathering_witness_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_of_gathering', to='action.steward'),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_of_gathering', to='action.steward'),
        ),
        migrations.AlterField(
            model_name='gathering_witness',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_of_gwitness', to='action.steward'),
        ),
        migrations.AlterField(
            model_name='gathering_witness',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_of_gwitness', to='action.steward'),
        ),
    ]
