# Generated by Django 4.1.7 on 2023-03-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_handle', models.CharField(blank=True, max_length=80, null=True)),
                ('admin_user_id', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True)),
                ('influence', models.PositiveIntegerField(blank=True, default=1000, null=True)),
                ('level', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.CharField(max_length=2000)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=80)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('quote_from', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_by_me', to='klapp.actor')),
                ('quote_to', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_to_me', to='klapp.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=2000)),
                ('media_url', models.CharField(max_length=80)),
                ('settings', models.CharField(max_length=2000)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('backers', models.ManyToManyField(blank=True, related_name='actions_backer', to='klapp.actor')),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='klapp.post')),
                ('comments', models.ManyToManyField(blank=True, related_name='comment_on', to='klapp.post')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='klapp.actor')),
                ('editors', models.ManyToManyField(blank=True, related_name='actions_editor', to='klapp.actor')),
                ('owners', models.ManyToManyField(blank=True, related_name='actions_owned', to='klapp.actor')),
                ('related_to', models.ManyToManyField(blank=True, related_name='posts_related', to='klapp.topic')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='conversation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='klapp.conversation'),
        ),
        migrations.AddField(
            model_name='actor',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='actors_following_me', to='klapp.actor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='history',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='klapp.quote'),
        ),
        migrations.AddField(
            model_name='actor',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='actors_interested', to='klapp.topic'),
        ),
    ]
