# Generated by Django 4.1.7 on 2023-03-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klapp', '0005_alter_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_from',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_by_me', to='klapp.actor'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_to',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_to_me', to='klapp.actor'),
        ),
    ]
